"""Notifier Lambda.

Runs on a schedule shortly after the collector. Queries the GSI for jobs
with status=SCORED and fit_score >= threshold, builds an HTML digest, and
sends via SES. Marks each sent job as status=SENT to avoid resending.
"""

from __future__ import annotations

import os
from datetime import datetime, timezone
from html import escape

import boto3

from shared import (
    configure_logging,
    get_table,
    log_json,
    mark_sent,
    query_scored_above_threshold,
)

log = configure_logging()


# ─────────────────────────────────────────────────────────────────────────────
# Email rendering
# ─────────────────────────────────────────────────────────────────────────────
VARIANT_LABEL = {
    "cloud_devops": "Cloud & DevOps",
    "sre": "SRE / Reliability",
    "fullstack": "Full-Stack JS",
    "industrial_iot": "Industrial IoT / OT",
}


def render_digest_html(jobs: list[dict], generated_at: datetime) -> str:
    if not jobs:
        return _empty_html(generated_at)

    rows = []
    for j in jobs:
        score = int(j.get("fit_score", 0))
        score_color = "#16a34a" if score >= 85 else ("#ca8a04" if score >= 75 else "#475569")
        variant = j.get("best_resume_variant", "?")
        variant_label = VARIANT_LABEL.get(variant, variant)
        matched = [s for s in j.get("matched_skills", set()) if s != "_none_"]
        gaps = [s for s in j.get("gaps", set()) if s != "_none_"]
        salary = _format_salary(j.get("salary_min"), j.get("salary_max"))

        rows.append(f"""
<tr>
  <td style="padding:16px 12px;border-bottom:1px solid #e2e8f0;vertical-align:top;">
    <div style="display:flex;align-items:center;gap:12px;margin-bottom:6px;">
      <span style="font-size:22px;font-weight:700;color:{score_color};">{score}</span>
      <span style="font-size:11px;color:#64748b;text-transform:uppercase;letter-spacing:0.05em;">
        Use <b>{escape(variant_label)}</b> resume
      </span>
    </div>
    <div style="font-size:16px;font-weight:600;color:#0f172a;margin-bottom:2px;">
      {escape(j.get('title', ''))}
    </div>
    <div style="font-size:14px;color:#334155;margin-bottom:6px;">
      {escape(j.get('company', ''))} &middot;
      {escape(j.get('location', ''))}
      {' &middot; <span style="color:#0891b2;">Remote</span>' if j.get('remote') else ''}
      {' &middot; ' + escape(salary) if salary else ''}
    </div>
    <div style="font-size:13px;color:#475569;line-height:1.5;margin-bottom:8px;">
      {escape(j.get('reasoning', ''))}
    </div>
    <div style="font-size:12px;color:#64748b;margin-bottom:4px;">
      <b>Matches:</b> {escape(', '.join(matched[:8])) if matched else '-'}
    </div>
    <div style="font-size:12px;color:#64748b;margin-bottom:10px;">
      <b>Gaps:</b> {escape(', '.join(gaps[:5])) if gaps else '-'}
    </div>
    <a href="{escape(j.get('apply_url', '#'))}"
       style="display:inline-block;padding:8px 14px;background:#0f172a;color:#ffffff;
              border-radius:6px;text-decoration:none;font-size:13px;font-weight:600;">
      View &amp; apply &rarr;
    </a>
    <span style="font-size:11px;color:#94a3b8;margin-left:10px;">
      from {escape(j.get('source', '?'))}
    </span>
  </td>
</tr>""")

    return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0;padding:24px;background:#f8fafc;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">
  <div style="max-width:680px;margin:0 auto;background:#ffffff;border-radius:12px;
              box-shadow:0 1px 3px rgba(0,0,0,0.05);overflow:hidden;">
    <div style="padding:24px;border-bottom:1px solid #e2e8f0;">
      <div style="font-size:20px;font-weight:700;color:#0f172a;">
        Job-Agent Digest
      </div>
      <div style="font-size:13px;color:#64748b;margin-top:4px;">
        {len(jobs)} match{'es' if len(jobs) != 1 else ''} &middot;
        {generated_at.strftime('%A, %B %d, %Y - %I:%M %p UTC')}
      </div>
    </div>
    <table style="width:100%;border-collapse:collapse;">{''.join(rows)}</table>
    <div style="padding:18px 24px;background:#f8fafc;font-size:12px;color:#94a3b8;text-align:center;">
      Generated by job-agent. Adjust threshold in <code>config.yaml</code>.
    </div>
  </div>
</body>
</html>"""


def _empty_html(generated_at: datetime) -> str:
    return f"""<!DOCTYPE html>
<html><body style="font-family:sans-serif;padding:24px;color:#475569;">
<p>No jobs above threshold for {generated_at.strftime('%Y-%m-%d %H:%M UTC')}.</p>
<p>Either the market is quiet right now or your threshold is too high.</p>
</body></html>"""


def render_digest_text(jobs: list[dict], generated_at: datetime) -> str:
    """Plain-text fallback for clients that won't render HTML."""
    if not jobs:
        return f"No jobs above threshold for {generated_at:%Y-%m-%d %H:%M UTC}."

    lines = [f"Job-Agent Digest - {generated_at:%Y-%m-%d %H:%M UTC}", "=" * 60, ""]
    for j in jobs:
        score = int(j.get("fit_score", 0))
        salary = _format_salary(j.get("salary_min"), j.get("salary_max"))
        lines.append(f"[{score}] {j.get('title')} - {j.get('company')}")
        lines.append(f"      {j.get('location')}{' (remote)' if j.get('remote') else ''}{' - ' + salary if salary else ''}")
        lines.append(f"      Resume: {VARIANT_LABEL.get(j.get('best_resume_variant', ''), '?')}")
        lines.append(f"      Why:    {j.get('reasoning', '')}")
        lines.append(f"      Apply:  {j.get('apply_url', '')}")
        lines.append("")
    return "\n".join(lines)


def _format_salary(lo, hi) -> str:
    if not lo and not hi:
        return ""
    if lo and hi:
        return f"${int(lo):,} - ${int(hi):,}"
    return f"${int(lo or hi):,}"


# ─────────────────────────────────────────────────────────────────────────────
# Handler
# ─────────────────────────────────────────────────────────────────────────────
def handler(event, context):
    threshold = int(os.environ.get("FIT_SCORE_THRESHOLD", "70"))
    sender = os.environ["SENDER_EMAIL"]
    recipient = os.environ["NOTIFICATION_EMAIL"]

    table = get_table()
    jobs = query_scored_above_threshold(table, threshold, limit=25)
    log_json(log, "info", "notifier_query", count=len(jobs), threshold=threshold)

    if not jobs:
        log_json(log, "info", "notifier_no_jobs")
        return {"sent": 0}

    generated_at = datetime.now(timezone.utc)
    html_body = render_digest_html(jobs, generated_at)
    text_body = render_digest_text(jobs, generated_at)
    subject = f"Job-Agent: {len(jobs)} matches ({generated_at:%b %d, %I%p UTC})"

    ses = boto3.client("ses")
    try:
        ses.send_email(
            Source=sender,
            Destination={"ToAddresses": [recipient]},
            Message={
                "Subject": {"Data": subject, "Charset": "UTF-8"},
                "Body": {
                    "Html": {"Data": html_body, "Charset": "UTF-8"},
                    "Text": {"Data": text_body, "Charset": "UTF-8"},
                },
            },
        )
    except Exception as e:
        log_json(log, "error", "ses_send_failed", error=str(e))
        raise

    # Mark all sent so they don't appear in tomorrow's digest.
    for j in jobs:
        try:
            mark_sent(table, j["pk"])
        except Exception as e:
            log_json(log, "warning", "mark_sent_failed", pk=j.get("pk"), error=str(e))

    log_json(log, "info", "notifier_done", sent=len(jobs))
    return {"sent": len(jobs)}
